### ISSUE TITLE
Test cases needed for Account class

### ISSUE THREAD

**Issue by smg134** [smg134/StreamVideo#5]
Need test cases for getName(), addStream(), report(), data(), and the constructor.

**Comment by smg134** [comment]
I added test cases, but I'm unsure of whether using a literal string is the right way to go about it. I'd appreciate if you all could look at the 'FIXME:' that I added to Account_t.cpp and let me know what you think.

**Comment by Kevin-Lewis** [comment]
I think it's fine. I can't think of any other way to test everything. 

I think we should add one more set of test cases for the data and report methods where we use a Movie instead of an Original since the output is slightly different in those cases. I can do one of each so that we're also testing multiple streams.

After that, we should be ready to start refactoring unless anyone sees any code we're not covering?

**Comment by rkg18** [comment]
I just took a look at the test cases for Account and everything seems fine. If you guys are happy with it we can push it to the master branch and close this. We can put in an issue on refactoring and we'll starting tackling that.
